return {
    mod_name = { en = "Server Ping" },
    mod_description = { en = "Measures latency to Darktide matchmaking regions." },
    open_server_ping = { en = "Open Server Ping" },
    open_server_ping_tooltip = { en = "Opens the server latency test while in the Mourningstar." },
    view_title = { en = "SERVER PING" },
    view_subtitle = { en = "Test Darktide's matchmaking endpoints. Estimated duration varies by connection." },
    header_region = { en = "REGION" },
    header_median = { en = "LATENCY" },
    header_average = { en = "AVERAGE" },
    header_minimum = { en = "MIN" },
    header_maximum = { en = "MAX" },
    header_jitter = { en = "JITTER" },
    header_loss = { en = "LOSS" },
    header_note = { en = "MATCHMAKING" },
    ping_servers = { en = "QUICK TEST\n~20 SEC" },
    detailed_test = { en = "DETAILED TEST\n~60 SEC" },
    history_button = { en = "HISTORY" },
    pinging_servers = { en = "PINGING..." },
    ping_cooldown = { en = "WAIT %ds" },
    status_idle = { en = "Quick uses 10 pings per endpoint. Detailed uses 30 pings per endpoint." },
    status_loading = { en = "Running %s test with %d pings per endpoint..." },
    status_complete = { en = "%d regions tested with %d pings per endpoint." },
    status_truncated = { en = "%d regions tested with %d pings per endpoint. Showing the fastest %d." },
    status_failed = { en = "The latency test failed. Please try again." },
    status_unavailable = { en = "The region latency service is not available yet." },
    status_cooldown = { en = "Please wait %d seconds before running another latency test." },
    history_title = { en = "PING HISTORY" },
    history_subtitle = { en = "Select a completed test to view its measurements." },
    history_tab_recent = { en = "RECENT" },
    history_tab_accumulated = { en = "ACCUMULATED" },
    history_aggregate_subtitle = { en = "%d tests accumulated from %s to %s." },
    history_aggregate_empty = { en = "No accumulated measurements are available yet." },
    history_date = { en = "DATE" },
    history_type = { en = "TYPE" },
    history_summary = { en = "SUMMARY" },
    history_region = { en = "REGION" },
    history_tests = { en = "TESTS" },
    history_network_totals = { en = "ACCUMULATED NETWORK RESULTS" },
    history_empty = { en = "No completed latency tests have been saved yet." },
    history_quick = { en = "QUICK" },
    history_detailed = { en = "DETAILED" },
    history_samples = { en = "%d pings per endpoint" },
    history_aggregate_row = { en = "AVG %dms | MIN-MAX %d-%dms | JITTER %dms | LOSS %d/%d (%.1f%%)" },
    history_detail_status = { en = "%s | %s test | %d pings per endpoint" },
    endpoint_title = { en = "%s ENDPOINTS" },
    endpoint_live_subtitle = { en = "Endpoint results from this measurement. Region selection lasts for this game session." },
    endpoint_aggregate_subtitle = { en = "Accumulated endpoint results. Region selection lasts for this game session." },
    endpoint_partial_subtitle = { en = "Endpoints from %d retained measurements; older region totals remain included. Selection is session-only." },
    endpoint_name = { en = "ENDPOINT" },
    endpoint_tests = { en = "TESTS" },
    previous_page = { en = "PREVIOUS" },
    next_page = { en = "NEXT" },
    use_this_region = { en = "USE THIS REGION" },
    region_selected = { en = "REGION SELECTED" },
    clear_history_confirm = { en = "Press Space again within 5 seconds to clear all history." },
    clear_history_done = { en = "All ping history and accumulated measurements were cleared." },
    status_hub_only = { en = "Server Ping is available in the Mourningstar." },
    status_busy = { en = "Server Ping is unavailable while matchmaking or the mission board is active." },
    result_timeout = { en = "Timed out" },
    result_recommended = { en = "RECOMMENDED" },
    result_selected = { en = "SELECTED" },
    select_region = { en = "SELECT REGION" },
    select_best_region = { en = "SELECT (BEST)" },
    result_none = { en = "--" },
    footer_hint = { en = "[Esc] Back    [Space] Clear all history" },
}
